name: GitHub Pages Builder
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: false  # since cf pages are used that's how we are going to disable this workflow
    # if: contains(github.event.head_commit.message, 'deploy')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install Yarn
        run: |
          npm install -g yarn@1.22.18
          yarn --version
          
      - name: Install dependencies
        run: yarn install
      
      - name: Build
        run: yarn build

      - name: Create CNAME
        run: |
          cd dist
          touch CNAME
          echo "genshin.zenless.club" > CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
